### ISSUE TITLE
User story 6 (Bookmark and Rating list)

### ISSUE THREAD

**Issue by FabianRuettgers** [FabianRuettgers/capstone-project#13]
## Value proposition

As a movie enthusiast, 
I want to see a list of films that I have saved and bookmarked 
in order to have future reference.

## Description

<img width="539" alt="Bildschirm­foto 2023-08-18 um 10 00 41" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/1b914069-ddd1-4647-b343-e0b6133931d6">
<img width="541" alt="Bildschirm­foto 2023-08-18 um 10 00 49" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/7ed90362-11dd-4926-93ab-c46cd8ea147a">

## Acceptance criteria

- a header with the title "Cinematrix" is displayed.
- a list of saved and rated movies is displayed.
- by clicking a movie, you get redirected to the details page
- a Picture, Title and added date is displayed.
- an appropriate message when the list is empty is displayed.
- a button to access the search form is displayed

## Tasks

- Create the branch feat/user-list
- Design the main page layout with the specified header and list of saved and rated movies.
- Implement the header with the title "Cinematrix."
- display the list of saved and rated movies from the localhost database.
- Implement the redirection to the movie details page when clicking on a movie.
- Display the movie's picture, title, and added date on the movie details page.
- Implement the message display for when the list of movies is empty.
- Design and implement the button to access the search form.
- Test the main page thoroughly, including clicking movies, verifying redirection, and responsiveness.
- Address any identified issues or errors to ensure a smooth user experience.

## Size

 Medium

**Comment by KevinKyaterekera** [comment]
Hey Fabian, LGTM. Very nice in detail 💪🏾 I think you could make small adjustments to the value proposition. 
You wrote: **I want to view a list** of films that I **have saved and bookmarked**. Your wireframe shows an "Film hinzufügen" button. Maybe you should erase this, if this wont be a function/task in this US. What do you think?

**Comment by KevinKyaterekera** [comment]
And you should write i want so see. Or i want to have a view 😉

**Comment by MiejkeHoltermann** [comment]
I think I would call the category "Bewertete Filme" like you did in the US. "Geschaute Filme" is a bit misleading, since I can watch a movie and not give a rating.
