### ISSUE TITLE
User story 2 (Details-Page)

### ISSUE THREAD

**Issue by FabianRuettgers** [FabianRuettgers/capstone-project#2]
## Value proposition

As a movie-lover,
I want to see a detailed movie-page
In order to get information of the movie

## Description

<img width="814" alt="Bildschirm­foto 2023-08-11 um 15 57 15" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/09e07f15-076f-4c68-b5dd-72578b5b7353">

## Acceptance criteria

- a header with the title "Film Details" and a button to navigate back to the previous page is displayed.
- the movie picture is displayed.
- the corresponding rating, genre, and the playtime in minutes is displayed.
- the movie title is displayed.
- the logos of the companies that provide options to buy, rent, and have flatrate subscriptions are shown.
- an appropriate error message is displayed, when all the content is empty.

## Tasks

- Create the branch feat/film-details.
- Design and implement a header component with the title "Film Details" and a navigation button to go back to the previous page.
- Create a component for displaying the movie picture.
- Create a component for displaying the corresponding rating, genre, and playtime in minutes.
- Create a component for displaying the movie title.
- Create a component to display logos of companies providing buy, rent, and flatrate options.
- Implement logic to fetch movie data from the backend, including details like picture, rating, genre, playtime, title, and company logos.
- Handle error scenarios by defining appropriate error messages for empty or failed data fetching.
- Ensure proper handling of requests from the frontend to the backend, including error cases like server unavailability.
- Design and implement error handling for scenarios where all content is empty, displaying a meaningful message to the user.
- Design the layout of the movie details page, considering the placement of different components, images, and logos.
- Design the appearance of alert messages for various scenarios, such as data fetching errors.
- Ensure the user interface is intuitive and visually appealing, aligning with the overall design aesthetics of the application.
- Test all the acceptance criteria to confirm that the movie details page functions correctly.

## Size
Medium

**Comment by milodevhh** [comment]
Hey Fabian, - "medium" love it, I think there is a lot to do, Maybe you split it in two US or?

**Comment by FabianRuettgers** [comment]
Hey Milo, It looks like much, but the API provides me with everything I need with a single fetch, so the most is plain styling. I can reuse my error component from my first user story, so medium should be right.
