### ISSUE TITLE
User story 9 (user-statistics)

### ISSUE THREAD

**Issue by FabianRuettgers** [FabianRuettgers/capstone-project#20]
## Value proposition

As a movie enthusiast platform,
I want to access a dedicated page that displays my user statistics and activity,
So that I can track my engagement and contributions to the movie community.

## Description

<img width="351" alt="Bildschirm­foto 2023-08-28 um 10 04 44" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/8013c2c4-a478-4edd-aa22-81c9287ba7a3">

## Acceptance criteria

- A new section is added to the user's profile menu, labeled as "User Statistics" or similar.
- The user can click on the "User Statistics" section from their profile menu to access the page.
- The page displays a summary of the user's activity, including the total number of comments and likes they have made across all movies.
- The user can view their most liked comments – a list of comments that have received the highest number of likes.
- The page design is intuitive and user-friendly, with clear labels and visual cues to help users understand their statistics.

## Tasks

- Create a new route or section for the "User Statistics" page.
- Design the layout of the page, incorporating interactive charts and lists for various statistics.
- Fetch and display the user's activity data, including comments, likes, and timestamps.
- Implement logic to generate the top commented movies and most liked comments lists.

## Size

Medium

**Comment by milodevhh** [comment]
Hey Fabian, sound fancy, have fun with that!
