### ISSUE TITLE
User story 10 (filter)

### ISSUE THREAD

**Issue by FabianRuettgers** [FabianRuettgers/capstone-project#22]
## Value proposition

As a movie enthusiast,
I want a seamless way to filter and discover movies based on their ratings,
So that I can easily find movies that match my preferences for quality and enjoyment.

## Description

<img width="468" alt="Bildschirm­foto 2023-08-30 um 10 27 25" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/4eddc04e-149d-4578-b3f1-e7db9a4a839b">

## Acceptance criteria

- A user-friendly movie filtering interface will be integrated into the platform, accessible from the movie listing page.
- Within the movie filtering interface, users will find a dedicated option to filter movies by their ratings.
- Users can choose a specific rating threshold (e.g., 4 stars and above) within the filtering options.
- Once a rating threshold is selected, the movie list will dynamically update, displaying only movies that meet or exceed the chosen rating threshold.
- In the event that no movies match the selected rating threshold, a clear message will be displayed to inform users about the absence of matching movies.

## Tasks

- Create a new branch called feat/filtering
- Design and implement the layout of the filtering options, including the rating threshold selector.
- Display a message when no movies match the selected rating threshold.
- Ensure that the filter settings are retained when returning from the detailed movie page.

## Size

Small

**Comment by F-Kirchhoff** [comment]
Hey Fabian,.
your user story is ready, but the wireframe doesn't show a filter but a sort functionality. Please update the wireframe such that it displays the UI elements for your filters.

**Comment by FabianRuettgers** [comment]
In the header will be a filtering SVG, as you can see in the first wireframe

**Comment by F-Kirchhoff** [comment]
The "Filter" Modal only displays ways to sort your list like rating high-low etc. Please change that such that it displays filtering logic.

**Comment by FabianRuettgers** [comment]
got it! so maybe something like this

**Comment by F-Kirchhoff** [comment]
Yeah, thats great!
