### ISSUE TITLE
User story 12 (Trailer)

### ISSUE THREAD

**Issue by FabianRuettgers** [FabianRuettgers/capstone-project#27]
## Value proposition

As a movie enthusiast,
I want to see a trailer on my movie details page,
In order to get a preview of the movie's visuals and storyline before deciding to watch it.

## Description

<img width="206" alt="Bildschirm­foto 2023-09-04 um 15 40 46" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/b6b61604-65f3-4456-95d2-19ff71db4795">

## Acceptance criteria

- When there is no trailer available for a movie, display a message indicating that there is no trailer.
- When a user clicks on the trailer, it should open in a new window or a modal for easy viewing.
- If the trailer fails to load or there is an error, display an alert with the message "Sorry, the trailer could not be loaded at this time. Please try again later."

## Tasks

- Design and implement the user interface for displaying the trailer.
- Implement the functionality to open the trailer in a new window or modal.
- Handle errors and display the appropriate alert messages.

## Size

small

**Comment by chris-kuehn** [comment]
Hi Fabian! I like your app a lot! was impressed during our public sprint review! A lot of Features and it looks very professional!

You have my go for the user story. one optional Idea: Inspite of shouing a text wich says no trailer Available, show a picture of the movie.

so you user wont miss anything if a trailor doesnt exsist.
