### ISSUE TITLE
User story 3 (Search-Form)

### ISSUE THREAD

**Issue by FabianRuettgers** [FabianRuettgers/capstone-project#3]
## Value proposition

As a movie-lover,
I want to be able to search for any movie
In order to get the movie displayed

## Description

<img width="659" alt="Bildschirm­foto 2023-08-11 um 16 06 25" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/567d9353-a863-47cf-a042-cd1ac9e584da">

<img width="661" alt="Bildschirm­foto 2023-08-11 um 16 07 47" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/2c76c03f-f4ac-4df0-b349-83ee6a19774c">

## Acceptance criteria

- a header with the title "Film suchen" and a button to navigate back to the previous page is displayed.
- an Input field is displayed.
- if the input is empty, a placeholder is displayed
- a Picture, Title and release year of a Movie according to the typed input is displayed.
- an appropriate Error-message when the input filed is empty is displayed.
- if the fetch was unsuccessful, an Error is displayed 

## Tasks

- Create the branch feat/movie-search.
- Design and implement a header component with the title "Film suchen" and a navigation button to go back to the previous page.
- Create a component for displaying the input field.
- Create a component to display the movie picture, title and release year based on the typed input.
- Implement logic to fetch movie data from the backend according to the search input, including picture, title and release year.
- Handle cases where the search input field is empty by displaying an appropriate message to guide the user.
- Define error handling to display a meaningful error message when all content (picture, title, release year) is empty due to invalid search input or no matches.
- Design the layout of the search results, considering the arrangement of components and information.
- Design the appearance of alert messages for different scenarios, such as no results found.
- Ensure the user interface is visually appealing and user-friendly, aligning with the overall design of the application.
- Test the acceptance criteria to ensure that the movie search functionality works correctly, including valid searches, empty searches, and non-matching queries.
- Test navigation between the search page and the previous page to confirm seamless integration.
- Validate that the displayed movie information corresponds accurately to the search input.

## Size
Medium

**Comment by ninaassmann** [comment]
LGTM

**Comment by milodevhh** [comment]
A real good one, have fun with that
