### ISSUE TITLE
User story 4 (Bookmarks)

### ISSUE THREAD

**Issue by FabianRuettgers** [FabianRuettgers/capstone-project#8]
## Value proposition

As a movie-lover,
I want to be able to save any movie 
In order to get the movie bookmarked

## Description

<img width="685" alt="Bildschirm­foto 2023-08-16 um 12 02 59" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/dfee936a-2588-46a8-8c73-4946c73d700f">

## Acceptance criteria

- a Button is displayed.
- Clicking the Button changes the UI to identify whether a Movie is bookmarked or not.

## Tasks

- Create the branch feat/bookmarks.
- Create a button for bookmarking items.
- Manage bookmarked status using a state variable.
- Persist bookmarked items using local storage.
- Change the look of the button to understand whether a movie is bookmarked or not.

## Size

Small

**Comment by MiejkeHoltermann** [comment]
Very nice! I'd just add one point to the acceptance criteria that the look of the button is supposed to change when you toggle it. Are you using a separate state variable for each item? Wouldn't it make sense to have one state variable with an array of all movie names and an isFavorite property?
