### ISSUE TITLE
User story 5 (Rate Movie)

### ISSUE THREAD

**Issue by FabianRuettgers** [FabianRuettgers/capstone-project#9]
## Value proposition

As a movie-lover,
I want to be able to rate any movie
In order to get my rating displayed

## Description

<img width="533" alt="Bildschirm­foto 2023-08-16 um 12 24 53" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/85099ab5-6181-453b-b4eb-998fd05929f9">

<img width="524" alt="Bildschirm­foto 2023-08-16 um 12 25 06" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/2abad342-e8e8-492f-843f-558a8e2f3bf3">

<img width="263" alt="Bildschirm­foto 2023-08-16 um 12 25 28" src="https://github.com/FabianRuettgers/capstone-project/assets/137037086/7ddb6d46-eed9-4586-ad90-55179fe12a1f">

## Acceptance criteria

- A "Rate Movie" button is displayed on the movie details page.
- Clicking the "Rate Movie" button triggers the display of a rating form.
- The rating form provides a way for users to input their rating, ranging from 1 to 10.
- Upon submitting the rating, the "Rate Movie" button disappears from the UI.
- Instead of the button, a "Rated" container emerges, displaying the submitted rating.
- A "Delete Rating" button becomes visible.
- Clicking the "Delete Rating" button removes the user's submitted rating.
- After deletion, the "Rated" container and the "Delete Rating" button vanish, reverting to the original "Rate Movie" button.
- The "Delete Rating" button remains hidden until the user submits a rating.

## Tasks

- create a new branch named feat/rating 
- Design a button to represent the "Rating" action
- Integrate the "Rating" button into the appropriate section of the movie details page
- Set up an onClick event handler for the button to trigger the rating process
- Develop a dedicated form component that allows users to input their rating for the movie
- Implement validation to ensure only numbers from 1 to 10 are accepted as valid ratings
- Implement a submission handler for the rating form
- after submitting a rating, display the submitted rating in a designated container
- Show a "Delete Rating" button alongside the displayed rating
- Set up a click event handler for the "Delete Rating" button
- Implement logic to remove the user's submitted rating from the displayed container
- Implement local storage to store users' submitted ratings
- Test the complete flow of rating submission, display, deletion, and statistics update

## Size

Medium

**Comment by mariusgolabski** [comment]
LGTM
